export const CHANGE_TITLE = 'CHANGE_TITLE';
export const TOGGLE_WEATHER_UNIT = 'TOGGLE_WEATHER_UNIT';
export const TOGGLE_SHOW_WIND = 'TOGGLE_SHOW_WIND';
export const SEND_REQUEST = 'SEND_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';